"""add users table

Revision ID: 2415f2bbc120
Revises: 
Create Date: 2022-03-08 03:10:54.073204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.utils.custom_fields
from app.auth.enums import SystemRoleEnum

# revision identifiers, used by Alembic.
revision = '2415f2bbc120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('login', sa.String(), nullable=False),
                    sa.Column('password', sa.LargeBinary(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('firstname', sa.String(), nullable=False),
                    sa.Column('lastname', sa.String(), nullable=False),
                    sa.Column('middlename', sa.String(), nullable=True),
                    sa.Column('role_type', app.utils.custom_fields.IntEnum(SystemRoleEnum), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
